### ISSUE TITLE
What's necessary?

### ISSUE THREAD

**Issue by codeofsumit** [nexeck/t1-sim#2]
Dear lovely T1 developer,

my name is Sumit from Tresor One. I would love to know what requirements you would like from the T1 API in an ideal scenario to make your library as efficient and user-friendly as possible. Would you be able to draft a wishlist here in the Github Issues?

I imagine something like an API-Key in the User-Settings for example (so no auth-header has to be copied).
Also, what about the rate-limit? Have you hit it? How do you get around it?
What would you recommend so the API is not spammed by scripts like these?

Thanks for your contribution to the T1 ecosystem - looking forward to get your thoughts

**Comment by nexeck** [comment]
Hello sumit,

thanks for reaching out to me for some feedback about the T1 API.

the main porpuse of this tool is backtesting different strategies. Current steps:
- WebUI: Create new Portfolio
- WebUI: Change Portfolio Name & public/private setting
- Tool: Create portfolio.csv
- Tool: Run tool
- WebUI: Upload transactions.csv
- WebUI: Watch and compare different portfolios/backtests
- WebUI: Delete unused Portfolios

In order to automate as much as possible, the following wishlist could help to achieve this:

- User based API-Key, which could be managed through the User-Settings
  - This would make it easier to use an api
- Dedicated API Endpoints with an OpenAPI documentation
  - Reverse engineering works, but it just may stop working and some data structures could make things easier for an API Only Endpoint (Creating portfolios as an example: Currentlly Create and then configure, could be done in one step)
- Portfolio API which allows management: Create/Configure (Maybe allow to set all settings during the creation), Delete & Purge all transactions/securities
  - I am not sure how the current transaction upload works, i guess its mostlly done inside the client browser? And API for this could complete the automation for this tool.
- Security Endpoint: For this tool, the one i am using has all the needed informations.

The rate-limit wasn't a problem, i got around this with a simple delay: https://github.com/nexeck/t1-sim/blob/main/src/generate.py#L84 . I haven't tested were exactly the limit is, the 0.5 seconds delay is okay.

Ideas to prevent spamming from tools like this:
- Keep the rate-limit, if not already in place: Different rate-limits for different endpoints (Portfolio creation could have another one)
- Bulk API Calls, for securitie prices it could be something like:
  - Send a List of dates to the API for one ISIN, and get all the prices back at once.
- In order to prevent the use of non API Endpoints in such Tools, you could use something like CSRF for the frontend <> backend communication

Best Regards
Marcel

**Comment by codeofsumit** [comment]
Thanks Marcel, that's great we will take this into account.
Please also make sure to properly make users aware that providing their authentication token is like giving you/this script their password with complete control over their account.

It's something we will address with scoped permissions when implementing API Keys.
